description: >
  The official Docker image for Vale. Includes 'py3-docutils' and 'asciidoctor'.
docker:
  - image: 'jdkato/vale:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific jdkato/vale image tag:
      https://hub.docker.com/r/jdkato/vale/tags
    type: string
