description: >
  cimg/base is an Ubuntu Docker image created by CircleCI with continuous integration builds in mind.
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: current
    description: >
      Pick a specific cimg/base image variant:
      https://circleci.com/developer/images/image/cimg/base
    type: string
